---
title: NOAA Storm Database exploring for US healt and economic consequences due to
  severe weather events
author: "Corrado Lanera"
date: "17 giugno 2015"
output: 
  html_document: 
    keep_md: yes
---

## Synopsis

* _Most 10 complete sentences_.


## Data Processing

* _Describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks_.


## Results


* _At least one figure containing a plot_.

* _Figures may have multiple plots in them (i.e. panel plots), but there cannot be more than three figures total_.


### Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

### Across the United States, which types of events have the greatest economic consequences?



## References

[1] National Weather Service Storm Data Documentation.

https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf

[2] National Climatic Data Center Storm Events FAQ.

https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf

[3] This assessment Git repo.

https://github.com/CorradoL/RepData_PeerAssessment2